# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a366c7cfd84c2503d979f86ec87f3ad476c011fcd9d06779a1ee28f592aeb1d7bd45774f51d84960e6a234c974e83916e38efa47ca524d1f5422ce451ac4f060

test:
  secret_key_base: d546e6ff8d19a9fe47a5dd4d10a0f103e21f1d12721a43cc3d1b3f472abc15dffb5b29e762930a7010c51739ac987536654aca14063e9e4524923f8edfa46d2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
